### PR TITLE
fixes #125

### LINKED ISSUE #125: Webpack host:port configuration
looks like webpack is trying to establish a connection on '/__webpack_hmr'
Problem is when loading the js into a page on another domain i need to configure webpack to connect back to a host of my choosing.

Is there some easy way of doing this? I can look into a pr if there isn't.
Thanks.

### PR DESCRIPTION
**Pull request by SeeThruHead**

### CODE REVIEW

**Comment by SeeThruHead** [comment]
Thinking further on this, maybe we can pass this query-string to the client by default?

**Comment by SeeThruHead** [comment]
@Yomguithereal Any thoughts on this? I'd like to get it working some way or another soonish.

**Comment by Yomguithereal** [comment]
What if you use a webpack config with the hmr endpoint? Does it work?

**Comment by SeeThruHead** [comment]
It's been working fine for me, all i'm doing is putting the proper url into the client script. I think this could actually be set to the kotatsu server url:port and there would be no need for a flag.

**Comment by Yomguithereal** [comment]
Yes. I guess this would be less cumbersome than a flag.

**Comment by Yomguithereal** [comment]
Sorry @SeeThruHead. I will close this as I don't remember what it was trying to solve nor if it is still relevant. Feel free to reopen the PR if this should still be fixed.

**Pull request closed without merging**
