### PR TITLE
Add --public to allow serving static assets

### LINKED ISSUE #68: Provide a `--public` flag, to serve static files
I'll take a crack at this myself

### PR DESCRIPTION
**Pull request by glenjamin**
Fixes #68

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Nice addition :). It would be even better with [yargs.duplicates](https://www.npmjs.com/package/yargs#duplicates) so that the user may pass more than one path if they wish so.

**Comment by Yomguithereal** [comment]
Do you want to do it or should I merge the PR and I'll handle the `duplicates` part later?

**Comment by glenjamin** [comment]
Happy to let you pick up the duplicates part

**Comment by Yomguithereal** [comment]
Fair enough :).

**Comment by Yomguithereal** [comment]
Do you see people needing to pass two arguments to do the following?

```js
app.use('/namespace', express.static(...));
```

**Comment by glenjamin** [comment]
I think you might be better off handling more complex cases via something like a `--configure-express` param, which points to a file that exports a module which will receive `app`.

**Pull request merged**
